// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDu34QjkGL6vyQjbOqDBP05KE_nYM69wMk',
    appId: '1:339631999877:web:5afb75154d88cc06db52ec',
    messagingSenderId: '339631999877',
    projectId: 'horizon-3f6ab',
    authDomain: 'horizon-3f6ab.firebaseapp.com',
    storageBucket: 'horizon-3f6ab.appspot.com',
    measurementId: 'G-JX1XRN4X7P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2PnoPdOUGvqycG44GUYMgdEDEJkAt1n0',
    appId: '1:339631999877:android:1b59654a69e53651db52ec',
    messagingSenderId: '339631999877',
    projectId: 'horizon-3f6ab',
    storageBucket: 'horizon-3f6ab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFKuC2dz-GWbGxYErPfIh7IXvat77f3ks',
    appId: '1:339631999877:ios:ea2e51925450fb68db52ec',
    messagingSenderId: '339631999877',
    projectId: 'horizon-3f6ab',
    storageBucket: 'horizon-3f6ab.appspot.com',
    iosBundleId: 'com.example.horizonProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFKuC2dz-GWbGxYErPfIh7IXvat77f3ks',
    appId: '1:339631999877:ios:ea2e51925450fb68db52ec',
    messagingSenderId: '339631999877',
    projectId: 'horizon-3f6ab',
    storageBucket: 'horizon-3f6ab.appspot.com',
    iosBundleId: 'com.example.horizonProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDu34QjkGL6vyQjbOqDBP05KE_nYM69wMk',
    appId: '1:339631999877:web:eee6169719c301d2db52ec',
    messagingSenderId: '339631999877',
    projectId: 'horizon-3f6ab',
    authDomain: 'horizon-3f6ab.firebaseapp.com',
    storageBucket: 'horizon-3f6ab.appspot.com',
    measurementId: 'G-H5YKY2EX6D',
  );
}
